# Generated by Django 4.1.7 on 2023-04-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_club_description_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['club', 'name']},
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='league_logos/'),
        ),
        migrations.AddField(
            model_name='players',
            name='image',
            field=models.ImageField(null=True, upload_to='players_images/'),
        ),
        migrations.AddField(
            model_name='players',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
