# Generated by Django 4.1.7 on 2023-04-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_players_options_club_logo_league_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['id']},
        ),
    ]
