# Generated by Django 4.1.7 on 2023-04-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_alter_comments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id']},
        ),
    ]
