# Generated by Django 4.1.7 on 2023-10-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_alter_players_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='image',
            field=models.ImageField(blank=True, default='footballer_icon', null=True, upload_to='players_images/'),
        ),
    ]
