# Generated by Django 4.1.7 on 2023-10-21 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_comments_date_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.comments'),
        ),
    ]
