# Generated by Django 4.2.7 on 2023-11-23 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.quotes'),
        ),
        migrations.AlterField(
            model_name='replies',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.comments'),
        ),
    ]
