# Generated by Django 4.2.7 on 2023-12-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_replies_quote_alter_replies_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself', max_length=100, null=True),
        ),
    ]
